apiVersion: apps/v1
kind: Deployment
metadata:
  name: message
  labels:
    app: message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message
  template:
    metadata:
      labels:
        app: message
        sidecar.istio.io/inject: "true"
    spec:
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: azurefile
      containers:
        - name: message
          image: "user22.azurecr.io/message:v1"
          ports:
            - containerPort: 8080
          env:
          - name: ORDER_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: ORDER_LOG_LEVEL
          volumeMounts:
          - mountPath: "/mnt/data"
            name: volume
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
