apiVersion: apps/v1
kind: Deployment
metadata:
  name: validate message
  labels:
    app: validate message
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validate message
  template:
    metadata:
      labels:
        app: validate message
    spec:
      containers:
        - name: validate message
          image: "username/validate message:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
